WSCC-84: Create E2E tests
mulesoft/mule-wsc-connector pull request #246
Opened 2020-08-31 16:12 UTC by gabrieldalborgo

2020-09-07 20:29 UTC, Bardammu requested changes

2020-09-07 20:29 UTC, Bardammu commented on pom.xml
> +            <version>1.1.3</version>
Add a version property for this new dependency

2020-09-07 20:29 UTC, Bardammu commented on src/main/java/org/mule/extension/ws/api/reliablemessaging/ReliableMessagingSettings.java
> +  private String wsrmSequence;
I'd add a `@Summary` maybe. Don't know it will help

2020-09-07 20:29 UTC, Bardammu commented on src/main/java/org/mule/extension/ws/api/reliablemessaging/ReliableMessagingConnectionSettings.java
> +  private ObjectStore wsrmStore;
I'd add a @Summary describing the use of it maybe. Don't know it will help

2020-09-07 20:29 UTC, Bardammu commented on src/test/java/org/mule/extension/ws/ConfigEqualsTestCase.java
> +    assertFalse(reliableMessaging.equals(new Object()));
You can use something like the following next time:
`assertThat(reliableMessaging,  is(notNullValue()));`
`assertThat(reliableMessaging, not(equalTo(new Object())));`
I think is prettier and more clear to understand when reading the logs

2020-09-07 20:58 UTC, gabrieldalborgo commented on pom.xml
> +            <version>1.1.3</version>
Done

2020-09-07 20:58 UTC, gabrieldalborgo commented on src/main/java/org/mule/extension/ws/api/reliablemessaging/ReliableMessagingSettings.java
> +  private String wsrmSequence;
Done

2020-09-07 20:58 UTC, gabrieldalborgo commented on src/main/java/org/mule/extension/ws/api/reliablemessaging/ReliableMessagingConnectionSettings.java
> +  private ObjectStore wsrmStore;
Done

2020-09-07 20:58 UTC, gabrieldalborgo commented on src/test/java/org/mule/extension/ws/ConfigEqualsTestCase.java
> +    assertFalse(reliableMessaging.equals(new Object()));
Done

2020-09-08 19:12 UTC, Bardammu approved these changes

2020-09-08 19:33 UTC, Bardammu approved these changes

2020-09-09 12:26 UTC, merged